import { ServiceCategory, ServiceItem, ProviderProfile } from './types';

export const ALL_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-tech',
    name: 'Technology & IT',
    slug: 'technology-it',
    description: 'Web development, mobile apps, software, cloud, AI, cybersecurity, and IT support.',
  },
  {
    id: 'cat-mktg',
    name: 'Digital & Marketing',
    slug: 'digital-marketing',
    description: 'SEO, local SEO, social media marketing, Google Ads, copywriting, and content creation.',
  },
  {
    id: 'cat-media',
    name: 'Media & Creative',
    slug: 'media-creative',
    description: 'Video editing, photography, 3D modeling, voice overs, graphic design, and panaflex.',
  },
  {
    id: 'cat-edu',
    name: 'Education & Tutoring',
    slug: 'education-tutoring',
    description: 'Home tutoring for Matric, FSc, O/A Levels, IELTS, programming, and exam prep.',
  },
  {
    id: 'cat-home',
    name: 'Home & Repair',
    slug: 'home-repair',
    description: 'Plumbing, electrician, AC jet wash, solar setup, refrigerator repair, and deep cleaning.',
  },
  {
    id: 'cat-const',
    name: 'Construction & Trades',
    slug: 'construction-trades',
    description: 'Masonry, tile fitting, marble polishing, welding, carpentry, roofing, and painting.',
  },
  {
    id: 'cat-auto',
    name: 'Automotive & Vehicles',
    slug: 'automotive',
    description: 'Mobile car mechanic, auto electrician, car washing, denting, painting, and tuning.',
  },
  {
    id: 'cat-life',
    name: 'Personal & Lifestyle',
    slug: 'personal-lifestyle',
    description: 'Tailoring, bridal makeup, mehndi, fitness trainer, event planning, and catering.',
  },
  {
    id: 'cat-biz',
    name: 'Business & Legal',
    slug: 'business-legal',
    description: 'FBR tax filing, bookkeeping, legal docs, HR consulting, and virtual assistants.',
  },
  {
    id: 'cat-agri',
    name: 'Agriculture & Gardening',
    slug: 'agriculture-gardening',
    description: 'Lawn landscaping, pest control spray, irrigation, tractor service, and nursery.',
  },
];

export const ALL_PROVIDERS: ProviderProfile[] = [
  {
    id: 'prov-101',
    cnicNumber: '42101-1234567-1',
    isVerified: true,
    hourlyRate: 1500,
    rating: 4.9,
    totalReviews: 84,
    serviceRadiusKm: 15,
    user: {
      id: 'usr-101',
      email: 'tariq.electrician@gmail.com',
      phone: '+92 300 1234567',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Tariq',
        lastName: 'Mahmood',
        city: 'Karachi',
        address: 'Gulshan-e-Iqbal Block 13-D, Karachi',
        bio: 'Licensed electrician with 12+ years experience in hybrid solar setups, UPS wiring, and DB load balancing.',
      },
    },
  },
  {
    id: 'prov-102',
    cnicNumber: '35202-9876543-3',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.85,
    totalReviews: 62,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-102',
      email: 'usman.ac@gmail.com',
      phone: '+92 321 9876543',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Usman',
        lastName: 'Ali',
        city: 'Lahore',
        address: 'Gulberg III, Main Boulevard, Lahore',
        bio: 'HVAC Master Technician in Inverter AC chemical jet wash, gas charging, and PCB circuit fixes.',
      },
    },
  },
  {
    id: 'prov-103',
    cnicNumber: '61101-4567890-5',
    isVerified: true,
    hourlyRate: 1200,
    rating: 4.75,
    totalReviews: 45,
    serviceRadiusKm: 12,
    user: {
      id: 'usr-103',
      email: 'rashid.plumber@gmail.com',
      phone: '+92 333 4567890',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Rashid',
        lastName: 'Khan',
        city: 'Islamabad',
        address: 'Sector G-11/3, Islamabad',
        bio: 'Plumbing expert specializing in underground pipeline leak detection, motor installation, and sanitary fittings.',
      },
    },
  },
  {
    id: 'prov-104',
    cnicNumber: '42201-3344556-7',
    isVerified: true,
    hourlyRate: 2000,
    rating: 4.95,
    totalReviews: 110,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-104',
      email: 'tech.dev.solutions@gmail.com',
      phone: '+92 345 5566778',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Faisal',
        lastName: 'Rehman',
        city: 'Karachi',
        address: 'PECHS Block 6, Karachi',
        bio: 'Full Stack Software Engineer & Tech Lead providing custom Web, Mobile, and Cloud Solutions across Pakistan.',
      },
    },
  },
];

// 134 UNIQUE REAL SERVICES ACROSS ALL 10 CATEGORIES
export const ALL_100_SERVICES: ServiceItem[] = [
  // --- 1. TECHNOLOGY & IT (20) ---
  {
    id: 'srv-tech-1',
    title: 'Custom Web Development (React & Next.js)',
    description: 'Full stack responsive web application development with modern frameworks, backend API integration, and fast performance.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-2',
    title: 'Mobile App Development (Flutter & React Native)',
    description: 'Cross-platform iOS and Android app development with user authentication, offline storage, and push notifications.',
    basePrice: 65000,
    durationMinutes: 600,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-3',
    title: 'Enterprise Software Development',
    description: 'Custom desktop & server enterprise software systems tailored for Pakistani inventory, accounting, and ERP needs.',
    basePrice: 85000,
    durationMinutes: 720,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-4',
    title: 'WordPress Website & Elementor Design',
    description: 'High converting custom WordPress setup, premium theme customization, WooCommerce shop integration, and security harding.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-5',
    title: 'E-commerce Store Development (Shopify / WooCommerce)',
    description: 'Complete online store setup with local payment gateways (JazzCash, EasyPaisa, PayFast), inventory management, and shipping rules.',
    basePrice: 35000,
    durationMinutes: 420,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-6',
    title: 'UI/UX Mobile & Web App Design (Figma)',
    description: 'User experience research, wireframing, high-fidelity interactive Figma prototypes, and design systems.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-7',
    title: 'Graphic Design & Vector Illustrations',
    description: 'Custom brand artwork, social media banners, marketing materials, and vector illustrations.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-8',
    title: 'Logo Design & Brand Identity Package',
    description: 'Professional vector logo design with complete brand guidelines, color palettes, and typography rules.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-9',
    title: 'Corporate Branding & Visual Identity',
    description: 'Complete business stationery, letterheads, business cards, merchandise design, and brand style guides.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-10',
    title: 'Database Architecture & SQL Development',
    description: 'PostgreSQL, MySQL, and MongoDB database design, query optimization, indexing, and migration pipelines.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-11',
    title: 'RESTful API & GraphQL Development',
    description: 'Secure API development using Node.js/NestJS/Python, JWT authorization, rate limiting, and OpenAPI documentation.',
    basePrice: 32000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-12',
    title: 'Cybersecurity Audit & Penetration Testing',
    description: 'Vulnerability assessment, OWASP web security testing, server hardening, and security compliance reporting.',
    basePrice: 40000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-13',
    title: 'Computer Networking & LAN/WAN Setup',
    description: 'Office network cabling, Mikrotik router configuration, Wi-Fi mesh setup, and VPN tunnel configuration.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-tech-14',
    title: 'On-Site IT Support & Computer Hardware Fixing',
    description: 'Troubleshooting desktop PCs, laptops, OS reinstallation, malware removal, and hardware upgrades.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-tech-15',
    title: 'Accurate Data Entry & Digitization',
    description: 'High-speed spreadsheet data entry, record cleanup, document scanning, and database data verification.',
    basePrice: 5000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-16',
    title: 'Data Processing & Excel Automation',
    description: 'Advanced Excel formula creation, VBA macro automation, PowerBI reporting, and data scrubbing.',
    basePrice: 10000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-17',
    title: 'Cloud Infrastructure Setup (AWS / GCP / Docker)',
    description: 'Deployment of containerized web apps on Cloud Run, AWS EC2, S3, SSL certificate setup, and CI/CD pipelines.',
    basePrice: 35000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-18',
    title: 'AI & Chatbot Integration Services',
    description: 'Custom Gemini API integration, automated customer service WhatsApp bots, and AI document search.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-19',
    title: 'Machine Learning Model Training',
    description: 'Predictive analytics, custom classification models, computer vision, and NLP model fine-tuning.',
    basePrice: 60000,
    durationMinutes: 600,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-tech-20',
    title: 'Software Quality Assurance & Automated Testing',
    description: 'Manual SQA, automated Cypress/Playwright regression testing, API Postman collections, and bug reporting.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[3],
  },

  // --- 2. DIGITAL & MARKETING (15) ---
  {
    id: 'srv-mktg-1',
    title: 'Comprehensive Digital Marketing Campaign',
    description: 'Multi-channel marketing strategy combining Google, Facebook, Instagram, and email lead generation for Pakistani brands.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-2',
    title: 'Search Engine Optimization (SEO)',
    description: 'On-page, technical, and off-page SEO optimization to rank websites on Google Page 1 for local search terms.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-3',
    title: 'Local SEO & Google My Business Setup',
    description: 'GMB profile creation, local citation building, customer review management, and local map pack ranking.',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-4',
    title: 'Social Media Marketing (SMM) Strategy',
    description: 'Targeted campaign management across Instagram, Facebook, and LinkedIn for local business growth.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-5',
    title: 'Social Media Page Management',
    description: 'Monthly content calendar, 15 custom posts/reels design, community engagement, and performance reporting.',
    basePrice: 22000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-6',
    title: 'Content Marketing & Brand Storytelling',
    description: 'Strategic content creation designed to build audience trust, educate buyers, and increase conversion rates.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-7',
    title: 'Email Marketing & Automated Sequence Setup',
    description: 'Mailchimp/Klaviyo email campaign design, newsletter creation, and automated welcome drip sequences.',
    basePrice: 14000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-8',
    title: 'Google Ads (PPC) Search & Display Campaigns',
    description: 'Keyword research, ad copy creation, conversion tracking setup, and ROI-optimized bidding strategy.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-9',
    title: 'Facebook & Instagram Paid Ads Management',
    description: 'Meta pixel setup, custom lookalike audience targeting, ad creative testing, and retargeting campaigns.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-10',
    title: 'TikTok Marketing & Viral Video Campaigns',
    description: 'Short-form video concept creation, trending audio strategy, influencer outreach, and TikTok ads setup.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-11',
    title: 'Sales Copywriting & Landing Page Copy',
    description: 'Persuasive sales page copy, website headers, email pitches, and ad copy engineered for high conversions.',
    basePrice: 10000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-12',
    title: 'Professional SEO Content Writing',
    description: 'Research-backed, keyword-rich web content, landing pages, and product descriptions in English and Urdu.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-13',
    title: 'Blog Article Writing & Publication',
    description: '1,500-word engaging blog posts tailored for your industry niche with royalty-free images and meta tags.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-14',
    title: 'English to Urdu Professional Translation',
    description: 'Accurate human translation of business legal documents, websites, marketing flyers, and user manuals.',
    basePrice: 6000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-mktg-15',
    title: 'Proofreading & Editing Services',
    description: 'Meticulous grammar, punctuation, sentence structure, and tone correction for academic and corporate documents.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[3],
  },

  // --- 3. MEDIA & CREATIVE (16) ---
  {
    id: 'srv-media-1',
    title: '4K Video Editing & Color Grading',
    description: 'Professional video post-production for YouTube videos, commercial ads, podcasts, and corporate promos.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-2',
    title: 'Professional Photo Retouching & Editing',
    description: 'High-end portrait retouching, background removal, skin smoothing, color balance, and photo manipulation.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-3',
    title: 'Event & Corporate Photography',
    description: 'On-location professional photography for corporate seminars, brand launch events, and commercial shoots.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-4',
    title: 'Studio Product Photography',
    description: 'High resolution e-commerce product photos with clean white background, lighting setup, and editing.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-5',
    title: 'Wedding & Event Coverage Photography',
    description: 'Full day coverage for Barat, Walima, and Mehendi events with DSLR setup and edited digital album.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-6',
    title: 'Cinematic Videography & Drone Filming',
    description: '4K cinematic video shoot using gimbal stabilization, studio lighting, and licensed 4K aerial drone footage.',
    basePrice: 35000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-7',
    title: '2D Explainer Video Animation',
    description: 'Engaging 2D character animation videos for business services, apps, and educational products.',
    basePrice: 22000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-8',
    title: 'Motion Graphics & Title Animations',
    description: 'Adobe After Effects title reveals, logo animations, lower thirds, and promo transition graphics.',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-9',
    title: '3D Product Design & Rendering',
    description: 'Photorealistic 3D product modeling, texturing, studio lighting, and high-res CAD rendering.',
    basePrice: 28000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-10',
    title: '3D Architectural Modeling & Visualizations',
    description: 'Blender / 3ds Max interior and exterior 3D architectural floorplan visualization and walkthroughs.',
    basePrice: 40000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-11',
    title: 'Urdu & English Voice Over Studio Services',
    description: 'Professional voice over recording for commercials, e-learning courses, IVR phone systems, and audiobooks.',
    basePrice: 10000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-12',
    title: 'Audio Editing & Podcast Mastering',
    description: 'Noise cleanup, background hiss removal, audio level normalization, and background score mixing.',
    basePrice: 7000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-13',
    title: 'Custom Music Production & Jingles',
    description: 'Original background music composition, sound design, jingles, and intro/outro sonic branding.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-14',
    title: 'Corporate Presentation & Pitch Deck Design',
    description: 'Investor pitch deck design in PowerPoint / Google Slides with custom graphics, infographics, and charts.',
    basePrice: 15000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-15',
    title: 'Brochure, Flyer & Print Design',
    description: 'Print-ready CMYK brochures, catalogs, flyers, and magazine ads with vector layout precision.',
    basePrice: 8000,
    durationMinutes: 150,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-media-16',
    title: 'Panaflex & Outdoor Signage Design',
    description: 'Large format outdoor billboard design, storefront panaflex boards, and vinyl banner graphics.',
    basePrice: 10000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[3],
  },

  // --- 4. EDUCATION & TUTORING (11) ---
  {
    id: 'srv-edu-1',
    title: 'School Home Tutoring (Class 1 to 8)',
    description: 'Qualified home tutor for all school subjects including Science, English, Maths, and Social Studies.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-2',
    title: 'Mathematics Home & Online Tutoring',
    description: 'Expert maths teacher for Metric, FSc, O-Level, and A-Level algebra, geometry, calculus, and statistics.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-3',
    title: 'Physics Tutoring (FSc & O/A Level)',
    description: 'Conceptual physics tutoring focusing on numerical problem solving, past papers, and lab practicals.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-4',
    title: 'Chemistry Home & Online Coaching',
    description: 'Organic, inorganic, and physical chemistry tutoring with past paper preparation for Cambridge & Federal board.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-5',
    title: 'Biology & Pre-Medical Tutoring',
    description: 'Coaching for FSc Pre-Medical and MDCAT biology preparation by experienced medical tutors.',
    basePrice: 16000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-6',
    title: 'Spoken English & Fluency Course',
    description: 'Interactive spoken English, accent training, grammar foundation, and conversational practice for adults and students.',
    basePrice: 10000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-7',
    title: 'Computer Science (ICS / O-Level) Tutoring',
    description: 'Computer theory, database concepts, algorithms, and logic gate preparation for board examinations.',
    basePrice: 14000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-edu-8',
    title: 'Python & JavaScript Programming Coaching',
    description: 'One-on-one coding lessons covering variables, loops, OOP, data structures, and mini project building.',
    basePrice: 20000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-edu-9',
    title: 'IELTS Academic & General Exam Prep',
    description: 'Comprehensive IELTS preparation covering Reading, Writing essays, Listening strategies, and Speaking mock tests.',
    basePrice: 18000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-10',
    title: 'Board Exam Preparation (Matric & FSc)',
    description: 'Targeted exam preparation, paper solving techniques, time management, and guess papers for top board marks.',
    basePrice: 14000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-edu-11',
    title: 'Online One-on-One Virtual Teaching',
    description: 'Flexible virtual teaching sessions via Zoom/Google Meet with screen share and interactive digital whiteboards.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[0],
  },

  // --- 5. HOME & REPAIR (15) ---
  {
    id: 'srv-home-1',
    title: 'Full House Deep Cleaning Service',
    description: 'Comprehensive house deep cleaning including floor scrubbing, window wiping, kitchen degreasing, and washrooms.',
    basePrice: 8500,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-2',
    title: 'Sofa & Carpet Steam Shampooing',
    description: 'Deep extraction steam cleaning for sofa sets, mattresses, and carpets removing stains and dust mites.',
    basePrice: 4500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-3',
    title: 'Sanitary & Pipe Leakage Plumbing Repair',
    description: 'Fixing leaking pipes, water mixer taps, underground seepage, drain unblocking, and shower installations.',
    basePrice: 2000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-home-4',
    title: 'Master Electrician & Home Wiring Check',
    description: 'Short circuit troubleshooting, new wiring installation, distribution board breaker upgrades, and earthing.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-5',
    title: 'Inverter AC Chemical Jet Service',
    description: 'High-pressure chemical jet wash for indoor and outdoor coils, drain pipe cleaning, and pressure check.',
    basePrice: 2500,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-6',
    title: 'AC Installation & Relocation Service',
    description: 'Safe copper piping installation, wall bracket mounting, vacuuming, and indoor unit level positioning.',
    basePrice: 4500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-7',
    title: 'Refrigerator & Deep Freezer Gas Charging',
    description: 'Compressor health test, gas leak fixing, thermostat replacement, and R134a/R600 gas topping up.',
    basePrice: 3800,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-8',
    title: 'Automatic Washing Machine Repair',
    description: 'Top-load and front-load washing machine drain motor, inlet valve, gear box, and PCB repair.',
    basePrice: 2800,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-9',
    title: 'Microwave Oven Circuit & Magnetron Repair',
    description: 'Fixing non-heating microwave ovens, glass plate turn motor replacement, touch panel fixing, and fuse setup.',
    basePrice: 2200,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-10',
    title: 'Gas / Petrol Generator Servicing & AVR Repair',
    description: 'Generator oil change, spark plug replacement, carburetor tuning, automatic voltage regulator (AVR) setup.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-11',
    title: 'Rooftop Solar Panel System Installation',
    description: '5kW to 20kW solar panel structure mounting, hybrid inverter wiring, DC breaker installation, and earthing.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-12',
    title: 'Solar Inverter Repair & Cleaning',
    description: 'Solar panel dust washing, inverter error code troubleshooting, MC4 connector replacement, and battery check.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-13',
    title: 'CCTV Camera System Installation',
    description: 'AHD / IP HD camera mounting, DVR/NVR configuration, mobile app remote viewing setup, and BNC wiring.',
    basePrice: 6000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-14',
    title: 'CCTV Camera Troubleshooting & Repair',
    description: 'Resolving video loss, night vision infrared issues, hard drive recording failures, and power supply repairs.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-15',
    title: 'Water Tank Cleaning & Disinfection',
    description: 'Underground and overhead water tank mud removal, chemical scrubbing, and chlorine disinfection.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[2],
  },

  // --- 6. CONSTRUCTION & TRADES (15) ---
  {
    id: 'srv-const-1',
    title: 'Iron Gate & Steel Welding Works',
    description: 'On-site electric arc welding, iron main gate repair, window grill fabrication, and steel structure reinforcement.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-2',
    title: 'Carpentry & Custom Wooden Furniture Repair',
    description: 'Fixing broken doors, drawer channels, wooden bed polish, door lock fitting, and custom wardrobe adjustments.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-3',
    title: 'Masonry & Brickwork Civil Repairs',
    description: 'Wall plastering, room extension brickwork, boundary wall repair, and cement grout sealing.',
    basePrice: 5000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-const-4',
    title: 'Floor & Wall Tile Installation',
    description: 'Porcelain and ceramic floor tile laying, bathroom wall tiling, laser alignment, and waterproof grouting.',
    basePrice: 12000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-const-5',
    title: 'Marble Polishing & Diamond Grinding',
    description: 'Sunny Gray, Ziarat White marble floor grinding, chemical mirror polish, and stain removal.',
    basePrice: 15000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-const-6',
    title: 'Full House Wall Painting & Waterproofing',
    description: 'Interior matt enamel paint, exterior weather-shield coating, dampness/seepage primer treatment, and wall putty.',
    basePrice: 20000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-7',
    title: 'Gypsum False Ceiling Installation',
    description: 'Modern gypsum board false ceiling design, cove lighting channels, and pop decorative plaster.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-8',
    title: 'Roof Seepage & Bitumen Heat Proofing',
    description: 'Rooftop water seepage prevention, elastomeric membrane coating, and heat reflective insulation paint.',
    basePrice: 16000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-const-9',
    title: 'Glass Door & Window Fitting',
    description: 'Tempered glass partition fitting, sliding door rollers repair, and frosted glass sheet application.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-10',
    title: 'Aluminium Section Window Fabrication',
    description: 'Custom aluminium sliding windows, insect screen net fitting, and weatherproof rubber seal installation.',
    basePrice: 14000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-11',
    title: 'Steel Structure & Shed Fabrication',
    description: 'Industrial steel truss shed building, parking shade installation, and heavy duty steel welding.',
    basePrice: 35000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-12',
    title: 'General Metal Fabrication Works',
    description: 'Custom iron staircase railings, balcony safety grills, and metal storage racks.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-13',
    title: 'Modular Kitchen Cabinet Assembly',
    description: 'UV sheet & tactile MDF kitchen cabinet installation, marble countertop cutting, and sink fitting.',
    basePrice: 22000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-14',
    title: 'Solid Wooden Door Installation',
    description: 'Wooden door frame (chokhat) fitting, solid wood door hanging, mortise lock installation, and polishing.',
    basePrice: 6000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-const-15',
    title: 'UPVC Window & Door Fitting',
    description: 'Double glazed energy efficient UPVC window installation, multi-point lock adjustment, and soundproofing.',
    basePrice: 16000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[0],
  },

  // --- 7. AUTOMOTIVE (12) ---
  {
    id: 'srv-auto-1',
    title: 'Mobile Car Mechanic On-Site Inspection',
    description: 'On-road emergency breakdown assistance, engine misfire troubleshooting, brake shoe replacement, and fluids top-up.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-2',
    title: 'Motorcycle General Repair & Engine Tuning',
    description: '70cc / 125cc bike oil change, carburetor cleaning, clutch plate check, chain adjustment, and brake tuning.',
    basePrice: 1200,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-3',
    title: 'Auto Electrician & Computer OBD Scanning',
    description: 'Computerized ECU fault code diagnosis, battery wiring check, alternator testing, and power window repair.',
    basePrice: 2500,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-4',
    title: 'Car AC Refrigerant Charging & Leak Test',
    description: 'Car AC cooling coil leak testing, compressor clutch check, and genuine R134a refrigerant gas refill.',
    basePrice: 3500,
    durationMinutes: 75,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-5',
    title: 'Doorstep Foam Car Wash & Vacuuming',
    description: 'Pressure foam car body wash, interior deep vacuuming, tire shine, and dashboard conditioning at home.',
    basePrice: 1800,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-6',
    title: 'Doorstep Heavy Bike Wash & Polish',
    description: 'High-pressure foam bike wash, chain degreasing & lubrication, and chrome polish treatment.',
    basePrice: 1000,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-7',
    title: 'Car Denting & Dry Dent Removal',
    description: 'Paintless dry dent removal for minor scratches, bumper realignment, and body panel repair.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-8',
    title: 'Car Touchup & Spray Painting',
    description: 'Computerized color matching, scratch touchup, clear coat spray, and body panel paint restoration.',
    basePrice: 8000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-9',
    title: 'Tire Puncture & Wheel Alignment Check',
    description: 'Tubeless tire puncture repair, wheel balancing, tire rotation, and air pressure check at doorstep.',
    basePrice: 1500,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-10',
    title: 'Car Battery Jumpstart & Replacement',
    description: 'Emergency car battery jumpstart, voltage health test, and on-site new AGS / Exide battery delivery.',
    basePrice: 1500,
    durationMinutes: 30,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-11',
    title: 'Comprehensive Pre-Purchase Car Inspection',
    description: '150-point technical car inspection covering engine, transmission, body paint gauge, suspension, and legal docs.',
    basePrice: 5000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-auto-12',
    title: 'EFI Engine Tuning & Throttle Body Cleaning',
    description: 'Catalytic converter cleaning, throttle body servicing, spark plug gap setting, and fuel injector testing.',
    basePrice: 4500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[1],
  },

  // --- 8. PERSONAL & LIFESTYLE (12) ---
  {
    id: 'srv-life-1',
    title: 'Custom Gents Tailoring & Suit Stitching',
    description: 'Master tailor stitching for Shalwar Kameez, Waistcoats, 2-piece & 3-piece formal suits with custom fitting.',
    basePrice: 3500,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-2',
    title: 'Bridal & Ladies Dress Designing',
    description: 'Custom designer stitching for Lehnga, Maxis, Designer Lawn suits, lace fitting, and embroidery work.',
    basePrice: 5000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-3',
    title: 'Doorstep Beauty & Facial Services',
    description: 'At-home herbal facial, waxing, threading, manicure, pedicure, and hair treatment for women.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-4',
    title: 'Gents Haircut & Beard Styling at Home',
    description: 'Professional barber haircut, charcoal facial, head massage, and precision beard grooming at your doorstep.',
    basePrice: 1500,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-5',
    title: 'Bridal & Party Makeup Artist',
    description: 'Professional HD bridal, Nikkah, and Barat makeup using genuine Kryolan / MAC cosmetics.',
    basePrice: 15000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-6',
    title: 'Organic Bridal & Eid Mehndi Design',
    description: 'Intricate Pakistani and Arabic organic henna designs for brides, family members, and Eid occasions.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-7',
    title: 'Personal Fitness Coach & Gym Instructor',
    description: 'Customized weight loss, muscle gain training, and diet plan coaching at home or local gym.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-8',
    title: 'Custom Nutrition & Weight Management Coaching',
    description: 'Personalized meal plans created according to Pakistani home food preferences and health goals.',
    basePrice: 6000,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-9',
    title: 'Complete Wedding & Birthday Event Planning',
    description: 'End-to-end event management including venue booking, floral stage setup, sound, lighting, and coordination.',
    basePrice: 50000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-10',
    title: 'Pakistani Cuisine Catering Services',
    description: 'Authentic Chicken/Mutton Biryani, Karahi, Seekh Kabab, and dessert catering for home parties and events.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-11',
    title: 'Themed Stage & Floral Decoration',
    description: 'Fresh flower stage decoration, balloon arches, fairy lights, and backdrop design for birthdays and engagement parties.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-life-12',
    title: 'Intercity Chauffeur & Driver Service',
    description: 'Verified professional driver for city errands or long distance trips across Punjab and Sindh.',
    basePrice: 3000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[0],
  },

  // --- 9. BUSINESS & LEGAL (10) ---
  {
    id: 'srv-biz-1',
    title: 'FBR Tax Return Filing & NTN Registration',
    description: 'FBR Iris portal tax return filing, wealth statement creation, active taxpayer list (ATL) status, and NTN issuance.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-2',
    title: 'Small Business Bookkeeping & Accounting',
    description: 'Monthly ledger maintenance, QuickBooks / Xero entry, financial statements, and balance sheet preparation.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-3',
    title: 'Sales Tax & SRB / PRA Registration',
    description: 'Sales tax registration with FBR, Sindh Revenue Board (SRB), or Punjab Revenue Authority (PRA).',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-4',
    title: 'SECP Private Limited Company Registration',
    description: 'End-to-end SECP company registration, incorporation certificate, memorandum of association, and digital signatures.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-5',
    title: 'Dedicated Virtual Assistant Services',
    description: 'Remote administrative support including email inbox management, appointment scheduling, and customer inquiries.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-6',
    title: 'Outsourced Customer Support Agent',
    description: '24/7 WhatsApp, live chat, and voice call support agent for e-commerce and local service businesses.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-7',
    title: 'HR Consulting & Employee Contract Drafting',
    description: 'Employee handbook creation, offer letters, NDA agreements, performance review frameworks, and payroll setup.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-8',
    title: 'Legal Partnership & Rent Agreement Drafting',
    description: 'Drafting legal deeds, tenancy agreements, partnership agreements, and affidavit attestation assistance.',
    basePrice: 8000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-9',
    title: 'ATS-Friendly CV & LinkedIn Optimization',
    description: 'Professional resume rewrite targeting ATS keyword screening, cover letter drafting, and LinkedIn profile redesign.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-biz-10',
    title: 'Business Feasibility & Financial Modeling',
    description: 'Comprehensive business startup financial projections, cashflow forecasts, and market feasibility reports.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[3],
  },

  // --- 10. AGRICULTURE & GARDENING (8) ---
  {
    id: 'srv-agri-1',
    title: 'Farm Soil Testing & Crop Consulting',
    description: 'Agricultural soil NPK analysis, crop disease advisory, fertilizer recommendations, and yield optimization.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-2',
    title: 'Drip & Sprinkler Irrigation Installation',
    description: 'Water-saving agricultural drip irrigation setup, solar pump connection, and filtration system installation.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-3',
    title: 'Agricultural Tractor & Land Laser Leveling',
    description: 'Tractor land plowing, rotavator soil turning, and precision GPS laser land leveling for farmlands.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-4',
    title: 'Termite & Anti-Pest Spray Treatment',
    description: 'Chemical termite proofing for home foundations, bedbug eradication, and agricultural crop pest spray.',
    basePrice: 6000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-5',
    title: 'Lawn Landscaping & Garden Design',
    description: 'Custom home lawn grass installation, rockery design, ornamental flower planting, and garden lighting.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-6',
    title: 'Regular Home Gardener Maintenance',
    description: 'Bi-weekly lawn mowing, hedge trimming, plant fertilization, weeding, and watering routine.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-7',
    title: 'Plant Nursery Delivery & Indoor Plants',
    description: 'Delivery of potted indoor plants, fruit saplings, organic soil manure, and ceramic planters.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-agri-8',
    title: 'Tree Pruning & Safe Removal Services',
    description: 'Safe trimming of overgrown tree branches near power lines, stump removal, and green waste disposal.',
    basePrice: 7000,
    durationMinutes: 150,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[2],
  },
];
