import { ServiceCategory, ServiceItem, ProviderProfile } from './types';

export const ALL_CATEGORIES: ServiceCategory[] = [
  {
    id: 'cat-tech',
    name: 'Technology & IT',
    slug: 'technology-it',
    description: 'Web development, mobile apps, software, cloud, AI, cybersecurity, and IT support.',
  },
  {
    id: 'cat-mktg',
    name: 'Digital & Marketing',
    slug: 'digital-marketing',
    description: 'SEO, local SEO, social media marketing, Google Ads, copywriting, and content creation.',
  },
  {
    id: 'cat-media',
    name: 'Media & Creative',
    slug: 'media-creative',
    description: 'Video editing, photography, 3D modeling, voice overs, graphic design, and panaflex.',
  },
  {
    id: 'cat-edu',
    name: 'Education & Tutoring',
    slug: 'education-tutoring',
    description: 'Home tutoring for Matric, FSc, O/A Levels, IELTS, programming, and exam prep.',
  },
  {
    id: 'cat-home',
    name: 'Home & Repair',
    slug: 'home-repair',
    description: 'Plumbing, electrician, AC jet wash, solar setup, refrigerator repair, and deep cleaning.',
  },
  {
    id: 'cat-const',
    name: 'Construction & Trades',
    slug: 'construction-trades',
    description: 'Masonry, tile fitting, marble polishing, welding, carpentry, roofing, and painting.',
  },
  {
    id: 'cat-auto',
    name: 'Automotive & Vehicles',
    slug: 'automotive',
    description: 'Mobile car mechanic, auto electrician, car washing, denting, painting, and tuning.',
  },
  {
    id: 'cat-life',
    name: 'Personal & Lifestyle',
    slug: 'personal-lifestyle',
    description: 'Tailoring, bridal makeup, mehndi, fitness trainer, event planning, and catering.',
  },
  {
    id: 'cat-biz',
    name: 'Business & Legal',
    slug: 'business-legal',
    description: 'FBR tax filing, bookkeeping, legal docs, HR consulting, and virtual assistants.',
  },
  {
    id: 'cat-agri',
    name: 'Agriculture & Gardening',
    slug: 'agriculture-gardening',
    description: 'Lawn landscaping, pest control spray, irrigation, tractor service, and nursery.',
  },
];

export const ALL_PROVIDERS: ProviderProfile[] = [
  // 0: Home & Repair - Master Electrician (Karachi)
  {
    id: 'prov-101',
    cnicNumber: '42101-1234567-1',
    isVerified: true,
    hourlyRate: 1500,
    rating: 4.9,
    totalReviews: 84,
    serviceRadiusKm: 15,
    user: {
      id: 'usr-101',
      email: 'tariq.electrician@gmail.com',
      phone: '+92 300 1234567',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Tariq',
        lastName: 'Mahmood',
        city: 'Karachi',
        address: 'Gulshan-e-Iqbal Block 13-D, Karachi',
        bio: 'Licensed master electrician with 12+ years experience in hybrid solar setups, 3-phase DB wiring, and UPS load balancing.',
      },
    },
  },
  // 1: Home & Repair - HVAC Master Technician (Lahore)
  {
    id: 'prov-102',
    cnicNumber: '35202-9876543-3',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.85,
    totalReviews: 62,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-102',
      email: 'usman.ac@gmail.com',
      phone: '+92 321 9876543',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Usman',
        lastName: 'Ali',
        city: 'Lahore',
        address: 'Gulberg III, Main Boulevard, Lahore',
        bio: 'HVAC Master Technician specializing in inverter AC high-pressure jet wash, R410A/R32 gas charging, and PCB circuit repair.',
      },
    },
  },
  // 2: Home & Repair - Plumbing Contractor (Islamabad)
  {
    id: 'prov-103',
    cnicNumber: '61101-4567890-5',
    isVerified: true,
    hourlyRate: 1200,
    rating: 4.75,
    totalReviews: 45,
    serviceRadiusKm: 12,
    user: {
      id: 'usr-103',
      email: 'rashid.plumber@gmail.com',
      phone: '+92 333 4567890',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Rashid',
        lastName: 'Khan',
        city: 'Islamabad',
        address: 'Sector G-11/3, Islamabad',
        bio: 'Certified plumbing contractor specializing in acoustic underground leak detection, pressure pumps, and sanitary fixtures.',
      },
    },
  },
  // 3: Home & Repair - Solar & Generator Specialist (Faisalabad)
  {
    id: 'prov-home-4',
    cnicNumber: '33100-2219481-5',
    isVerified: true,
    hourlyRate: 1400,
    rating: 4.88,
    totalReviews: 59,
    serviceRadiusKm: 18,
    user: {
      id: 'usr-home-4',
      email: 'asif.solar@gmail.com',
      phone: '+92 341 2219481',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Asif',
        lastName: 'Mehmood',
        city: 'Faisalabad',
        address: 'Peoples Colony No. 1, Faisalabad',
        bio: 'Solar inverter engineer and lithium battery maintenance specialist certified for DISCO net-metering compliance.',
      },
    },
  },
  // 4: Tech & IT - Full Stack Software Engineer (Karachi)
  {
    id: 'prov-104',
    cnicNumber: '42201-3344556-7',
    isVerified: true,
    hourlyRate: 2000,
    rating: 4.95,
    totalReviews: 110,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-104',
      email: 'tech.dev.solutions@gmail.com',
      phone: '+92 345 5566778',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Faisal',
        lastName: 'Rehman',
        city: 'Karachi',
        address: 'PECHS Block 6, Karachi',
        bio: 'Full Stack Software Engineer & Tech Lead providing custom Next.js, React, Node.js, and cloud architectures.',
      },
    },
  },
  // 5: Tech & IT - Mobile App Engineer (Lahore)
  {
    id: 'prov-tech-2',
    cnicNumber: '35201-8842193-1',
    isVerified: true,
    hourlyRate: 2200,
    rating: 4.88,
    totalReviews: 76,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-tech-2',
      email: 'hamza.flutter@gmail.com',
      phone: '+92 334 8842193',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Hamza',
        lastName: 'Ali',
        city: 'Lahore',
        address: 'Johar Town Phase 2, Lahore',
        bio: 'Senior Flutter and React Native mobile developer with 15+ production apps released on iOS App Store and Play Store.',
      },
    },
  },
  // 6: Tech & IT - DevOps & Cloud Architect (Islamabad)
  {
    id: 'prov-tech-3',
    cnicNumber: '61101-7721094-5',
    isVerified: true,
    hourlyRate: 2500,
    rating: 4.92,
    totalReviews: 58,
    serviceRadiusKm: 22,
    user: {
      id: 'usr-tech-3',
      email: 'bilal.cloud@gmail.com',
      phone: '+92 312 7721094',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Bilal',
        lastName: 'Ahmed',
        city: 'Islamabad',
        address: 'Blue Area, Sector F-6, Islamabad',
        bio: 'AWS & Kubernetes certified cloud architect specializing in CI/CD automation, server security, and zero-downtime deployments.',
      },
    },
  },
  // 7: Digital & Marketing - SEO Specialist (Lahore)
  {
    id: 'prov-mktg-1',
    cnicNumber: '35202-6612984-2',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.91,
    totalReviews: 93,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-mktg-1',
      email: 'zainab.seo@gmail.com',
      phone: '+92 301 6612984',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Zainab',
        lastName: 'Fatima',
        city: 'Lahore',
        address: 'DHA Phase 3, Lahore',
        bio: 'Google Search Console and Analytics certified specialist focusing on local SEO map-pack rankings and technical audits.',
      },
    },
  },
  // 8: Digital & Marketing - Meta & Google Ads Specialist (Karachi)
  {
    id: 'prov-mktg-2',
    cnicNumber: '42101-5521943-3',
    isVerified: true,
    hourlyRate: 2000,
    rating: 4.86,
    totalReviews: 68,
    serviceRadiusKm: 30,
    user: {
      id: 'usr-mktg-2',
      email: 'saad.ads@gmail.com',
      phone: '+92 322 5521943',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Saad',
        lastName: 'Qureshi',
        city: 'Karachi',
        address: 'Clifton Block 5, Karachi',
        bio: 'Performance marketing manager managing high ROAS PPC advertising on Google Search, YouTube, and Meta for Pakistani brands.',
      },
    },
  },
  // 9: Digital & Marketing - Copywriter & Content Strategist (Rawalpindi)
  {
    id: 'prov-mktg-3',
    cnicNumber: '37405-3319082-6',
    isVerified: true,
    hourlyRate: 1600,
    rating: 4.89,
    totalReviews: 54,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-mktg-3',
      email: 'ayesha.copy@gmail.com',
      phone: '+92 331 3319082',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Ayesha',
        lastName: 'Malik',
        city: 'Rawalpindi',
        address: 'Bahria Town Phase 4, Rawalpindi',
        bio: 'B2B/B2C copywriter crafting high-converting sales letters, social media calendars, and bilingual press releases.',
      },
    },
  },
  // 10: Media & Creative - Commercial Video Producer (Karachi)
  {
    id: 'prov-media-1',
    cnicNumber: '42301-4491823-1',
    isVerified: true,
    hourlyRate: 2200,
    rating: 4.94,
    totalReviews: 82,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-media-1',
      email: 'shahmeer.video@gmail.com',
      phone: '+92 304 4491823',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Shahmeer',
        lastName: 'Abbas',
        city: 'Karachi',
        address: 'Gulistan-e-Jauhar Block 7, Karachi',
        bio: 'Commercial video director and DaVinci Resolve colorist specializing in 4K ad films, YouTube production, and drone footage.',
      },
    },
  },
  // 11: Media & Creative - Brand & UI/UX Designer (Lahore)
  {
    id: 'prov-media-2',
    cnicNumber: '35201-7729104-4',
    isVerified: true,
    hourlyRate: 1900,
    rating: 4.9,
    totalReviews: 71,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-media-2',
      email: 'hina.design@gmail.com',
      phone: '+92 323 7729104',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Hina',
        lastName: 'Siddiqui',
        city: 'Lahore',
        address: 'Model Town Block C, Lahore',
        bio: 'Brand identity and UI designer crafting vector logos, print typography, packaging, and clean mobile UI mockups.',
      },
    },
  },
  // 12: Media & Creative - Voiceover & Audio Engineer (Islamabad)
  {
    id: 'prov-media-3',
    cnicNumber: '61101-2291034-7',
    isVerified: true,
    hourlyRate: 1700,
    rating: 4.85,
    totalReviews: 49,
    serviceRadiusKm: 15,
    user: {
      id: 'usr-media-3',
      email: 'mustafa.audio@gmail.com',
      phone: '+92 332 2291034',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Mustafa',
        lastName: 'Kamal',
        city: 'Islamabad',
        address: 'Sector I-8/2, Islamabad',
        bio: 'Professional Urdu & English voiceover artist with an acoustic-treated home studio for commercials, audiobooks, and IVR.',
      },
    },
  },
  // 13: Education & Tutoring - O/A Levels Science Tutor (Karachi)
  {
    id: 'prov-edu-1',
    cnicNumber: '42101-8829104-9',
    isVerified: true,
    hourlyRate: 2000,
    rating: 4.97,
    totalReviews: 124,
    serviceRadiusKm: 15,
    user: {
      id: 'usr-edu-1',
      email: 'noman.tutor@gmail.com',
      phone: '+92 300 8829104',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Dr. Noman',
        lastName: 'Rauf',
        city: 'Karachi',
        address: 'North Nazimabad Block H, Karachi',
        bio: 'Senior Cambridge certified teacher with 15+ years coaching O & A Level Physics, Chemistry, and Additional Mathematics.',
      },
    },
  },
  // 14: Education & Tutoring - FSc & MDCAT Instructor (Lahore)
  {
    id: 'prov-edu-2',
    cnicNumber: '35202-4410293-8',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.92,
    totalReviews: 88,
    serviceRadiusKm: 18,
    user: {
      id: 'usr-edu-2',
      email: 'maryam.bio@gmail.com',
      phone: '+92 321 4410293',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Maryam',
        lastName: 'Jamil',
        city: 'Lahore',
        address: 'Faisal Town, Lahore',
        bio: 'MSc Biology gold medalist providing structured home and online tutoring for Punjab Board FSc Pre-Medical and MDCAT entry test.',
      },
    },
  },
  // 15: Education & Tutoring - IELTS 8.5 Master Coach (Islamabad)
  {
    id: 'prov-edu-3',
    cnicNumber: '61101-5529183-3',
    isVerified: true,
    hourlyRate: 2200,
    rating: 4.89,
    totalReviews: 95,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-edu-3',
      email: 'farhan.ielts@gmail.com',
      phone: '+92 333 5529183',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Farhan',
        lastName: 'Baig',
        city: 'Islamabad',
        address: 'Sector F-10/4, Islamabad',
        bio: 'British Council certified IELTS Academic & General trainer (Band 8.5) and professional corporate English trainer.',
      },
    },
  },
  // 16: Construction & Trades - Master Mason & Tile Setter (Lahore)
  {
    id: 'prov-const-1',
    cnicNumber: '35201-3391820-7',
    isVerified: true,
    hourlyRate: 1400,
    rating: 4.87,
    totalReviews: 67,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-const-1',
      email: 'ghulam.mason@gmail.com',
      phone: '+92 302 3391820',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Ghulam',
        lastName: 'Rasool',
        city: 'Lahore',
        address: 'Allama Iqbal Town, Lahore',
        bio: 'Master Mason and porcelain tile setter with 18+ years experience in Spanish tile laying, marble diamond polishing, and plaster.',
      },
    },
  },
  // 17: Construction & Trades - Custom Carpenter (Karachi)
  {
    id: 'prov-const-2',
    cnicNumber: '42101-9921034-1',
    isVerified: true,
    hourlyRate: 1500,
    rating: 4.83,
    totalReviews: 52,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-const-2',
      email: 'kashif.wood@gmail.com',
      phone: '+92 322 9921034',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Kashif',
        lastName: 'Javed',
        city: 'Karachi',
        address: 'Federal B Area Block 14, Karachi',
        bio: 'Architectural woodworker specializing in modular kitchen cabinets, high-gloss UV sheet wardrobes, and solid wood doors.',
      },
    },
  },
  // 18: Construction & Trades - Welder & Fabricator (Rawalpindi)
  {
    id: 'prov-const-3',
    cnicNumber: '37405-6619283-9',
    isVerified: true,
    hourlyRate: 1300,
    rating: 4.86,
    totalReviews: 44,
    serviceRadiusKm: 22,
    user: {
      id: 'usr-const-3',
      email: 'waheed.weld@gmail.com',
      phone: '+92 334 6619283',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Abdul',
        lastName: 'Waheed',
        city: 'Rawalpindi',
        address: 'Westridge 1, Peshawar Road, Rawalpindi',
        bio: 'Certified structural welder specializing in laser-cut safety gates, spiral iron stairs, window safety grills, and sheds.',
      },
    },
  },
  // 19: Automotive & Vehicles - EFI Engine Specialist (Lahore)
  {
    id: 'prov-auto-1',
    cnicNumber: '35202-7719284-5',
    isVerified: true,
    hourlyRate: 1600,
    rating: 4.93,
    totalReviews: 102,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-auto-1',
      email: 'naveed.auto@gmail.com',
      phone: '+92 301 7719284',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Naveed',
        lastName: 'Akhtar',
        city: 'Lahore',
        address: 'Walton Road, Cantt, Lahore',
        bio: 'Chief EFI Diagnostic Specialist with computer OBD-II scanner tools for Japanese, European, and Pakistani automobiles.',
      },
    },
  },
  // 20: Automotive & Vehicles - Auto Electrician & Hybrid Tech (Karachi)
  {
    id: 'prov-auto-2',
    cnicNumber: '42201-5510293-3',
    isVerified: true,
    hourlyRate: 1500,
    rating: 4.88,
    totalReviews: 79,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-auto-2',
      email: 'sohail.hybrid@gmail.com',
      phone: '+92 321 5510293',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Sohail',
        lastName: 'Akhtar',
        city: 'Karachi',
        address: 'Korangi Industrial Area Road, Karachi',
        bio: 'Certified hybrid battery technician (Aqua, Prius, Vezel) and auto electrician for wiring harness and ECM sensor repair.',
      },
    },
  },
  // 21: Automotive & Vehicles - Mobile Detailing & Ceramic Coat (Islamabad)
  {
    id: 'prov-auto-3',
    cnicNumber: '61101-9921048-1',
    isVerified: true,
    hourlyRate: 1700,
    rating: 4.85,
    totalReviews: 63,
    serviceRadiusKm: 18,
    user: {
      id: 'usr-auto-3',
      email: 'waqar.detail@gmail.com',
      phone: '+92 333 9921048',
      avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Waqar',
        lastName: 'Butt',
        city: 'Islamabad',
        address: 'Sector G-8/1, Islamabad',
        bio: 'Doorstep car detailing, Meguiars 3-stage compound buffing, 9H ceramic coating, and steam interior sanitization.',
      },
    },
  },
  // 22: Personal & Lifestyle - Bridal & Party Makeup Artist (Lahore)
  {
    id: 'prov-life-1',
    cnicNumber: '35202-1192847-6',
    isVerified: true,
    hourlyRate: 2500,
    rating: 4.96,
    totalReviews: 115,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-life-1',
      email: 'saba.makeup@gmail.com',
      phone: '+92 305 1192847',
      avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Saba',
        lastName: 'Tahir',
        city: 'Lahore',
        address: 'Gulberg II, Lahore',
        bio: 'Certified luxury bridal makeup artist and hairstylist offering at-home Barat, Walima, and photoshoot makeup services.',
      },
    },
  },
  // 23: Personal & Lifestyle - Fitness & Nutrition Coach (Karachi)
  {
    id: 'prov-life-2',
    cnicNumber: '42101-6629104-5',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.89,
    totalReviews: 73,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-life-2',
      email: 'kamran.fitness@gmail.com',
      phone: '+92 322 6629104',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Kamran',
        lastName: 'Yousuf',
        city: 'Karachi',
        address: 'DHA Phase 6, Karachi',
        bio: 'Certified personal fitness trainer providing home workouts, posture correction, and tailored Desi diet plans for fat loss.',
      },
    },
  },
  // 24: Personal & Lifestyle - Master Bespoke Tailor (Rawalpindi)
  {
    id: 'prov-life-3',
    cnicNumber: '37405-8821903-7',
    isVerified: true,
    hourlyRate: 1400,
    rating: 4.84,
    totalReviews: 58,
    serviceRadiusKm: 15,
    user: {
      id: 'usr-life-3',
      email: 'rafiq.tailor@gmail.com',
      phone: '+92 331 8821903',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Master',
        lastName: 'Rafiq',
        city: 'Rawalpindi',
        address: 'Saddar, Bank Road, Rawalpindi',
        bio: 'Master Tailor with 25+ years in doorstep measurement and bespoke stitching of gents Shalwar Kameez, Waistcoats, and Prince coats.',
      },
    },
  },
  // 25: Business & Legal - High Court Advocate & Corporate Counsel (Islamabad)
  {
    id: 'prov-biz-1',
    cnicNumber: '61101-3319082-9',
    isVerified: true,
    hourlyRate: 3000,
    rating: 4.94,
    totalReviews: 91,
    serviceRadiusKm: 30,
    user: {
      id: 'usr-biz-1',
      email: 'rizwan.legal@gmail.com',
      phone: '+92 300 3319082',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Advocate Rizwan',
        lastName: 'Abbasi',
        city: 'Islamabad',
        address: 'High Court Bar, G-10/1, Islamabad',
        bio: 'High Court Advocate specializing in SECP Pvt Ltd company incorporation, trademark registration, and partnership deeds.',
      },
    },
  },
  // 26: Business & Legal - Chartered Tax Practitioner & FBR Filing (Karachi)
  {
    id: 'prov-biz-2',
    cnicNumber: '42101-7729104-3',
    isVerified: true,
    hourlyRate: 2000,
    rating: 4.91,
    totalReviews: 108,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-biz-2',
      email: 'taha.tax@gmail.com',
      phone: '+92 321 7729104',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Taha',
        lastName: 'Siddiqui',
        city: 'Karachi',
        address: 'I.I. Chundrigar Road, Karachi',
        bio: 'Active Tax Practitioner and accountant assisting salaried individuals and business owners with FBR Iris filing and wealth statements.',
      },
    },
  },
  // 27: Business & Legal - HR & Corporate Operations (Lahore)
  {
    id: 'prov-biz-3',
    cnicNumber: '35201-9912038-4',
    isVerified: true,
    hourlyRate: 1800,
    rating: 4.87,
    totalReviews: 46,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-biz-3',
      email: 'nida.hr@gmail.com',
      phone: '+92 332 9912038',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Nida',
        lastName: 'Parvez',
        city: 'Lahore',
        address: 'Gulberg III, Lahore',
        bio: 'HR Consultant and operations expert structuring employee handbooks, employment contracts, and remote team payroll systems.',
      },
    },
  },
  // 28: Agriculture & Gardening - Landscape Architect & Horticulturist (Islamabad)
  {
    id: 'prov-agri-1',
    cnicNumber: '61101-4419203-5',
    isVerified: true,
    hourlyRate: 1500,
    rating: 4.9,
    totalReviews: 77,
    serviceRadiusKm: 25,
    user: {
      id: 'usr-agri-1',
      email: 'jahangir.landscape@gmail.com',
      phone: '+92 303 4419203',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Malik',
        lastName: 'Jahangir',
        city: 'Islamabad',
        address: 'Park Road, Chak Shahzad, Islamabad',
        bio: 'Degree-holding Horticulturist creating rooftop kitchen gardens, Korean grass lawns, and automated drip watering systems.',
      },
    },
  },
  // 29: Agriculture & Gardening - Agronomist & Solar Drip Irrigation (Multan)
  {
    id: 'prov-agri-2',
    cnicNumber: '36302-8819204-1',
    isVerified: true,
    hourlyRate: 1400,
    rating: 4.86,
    totalReviews: 53,
    serviceRadiusKm: 40,
    user: {
      id: 'usr-agri-2',
      email: 'bashir.farm@gmail.com',
      phone: '+92 301 8819204',
      avatarUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Chaudhry',
        lastName: 'Bashir',
        city: 'Multan',
        address: 'Vehari Road, Multan',
        bio: 'Agricultural advisor with 20+ years in fruit orchard pest management, soil nutrient testing, and solar tube-well setups.',
      },
    },
  },
  // 30: Agriculture & Gardening - Urban Gardener & Nursery Expert (Lahore)
  {
    id: 'prov-agri-3',
    cnicNumber: '35202-5519283-7',
    isVerified: true,
    hourlyRate: 1200,
    rating: 4.88,
    totalReviews: 64,
    serviceRadiusKm: 20,
    user: {
      id: 'usr-agri-3',
      email: 'sultan.gardens@gmail.com',
      phone: '+92 322 5519283',
      avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      profile: {
        firstName: 'Sultan',
        lastName: 'Ali',
        city: 'Lahore',
        address: 'Bedian Road, Cantt, Lahore',
        bio: 'Professional gardener providing seasonal flower planting, organic lawn weed eradication, and ornamental shrub pruning.',
      },
    },
  },
];

// 134 UNIQUE REAL SERVICES ACROSS ALL 10 CATEGORIES
export const ALL_100_SERVICES: ServiceItem[] = [
  // --- 1. TECHNOLOGY & IT (20) ---
  {
    id: 'srv-tech-1',
    title: 'Custom Web Development (React & Next.js)',
    description: 'Full stack responsive web application development with modern frameworks, backend API integration, and fast performance.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-2',
    title: 'Mobile App Development (Flutter & React Native)',
    description: 'Cross-platform iOS and Android app development with user authentication, offline storage, and push notifications.',
    basePrice: 65000,
    durationMinutes: 600,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-3',
    title: 'Enterprise Software Development',
    description: 'Custom desktop & server enterprise software systems tailored for Pakistani inventory, accounting, and ERP needs.',
    basePrice: 85000,
    durationMinutes: 720,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-4',
    title: 'WordPress Website & Elementor Design',
    description: 'High converting custom WordPress setup, premium theme customization, WooCommerce shop integration, and security harding.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-5',
    title: 'E-commerce Store Development (Shopify / WooCommerce)',
    description: 'Complete online store setup with local payment gateways (JazzCash, EasyPaisa, PayFast), inventory management, and shipping rules.',
    basePrice: 35000,
    durationMinutes: 420,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-6',
    title: 'UI/UX Mobile & Web App Design (Figma)',
    description: 'User experience research, wireframing, high-fidelity interactive Figma prototypes, and design systems.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-7',
    title: 'Graphic Design & Vector Illustrations',
    description: 'Custom brand artwork, social media banners, marketing materials, and vector illustrations.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-8',
    title: 'Logo Design & Brand Identity Package',
    description: 'Professional vector logo design with complete brand guidelines, color palettes, and typography rules.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-9',
    title: 'Corporate Branding & Visual Identity',
    description: 'Complete business stationery, letterheads, business cards, merchandise design, and brand style guides.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-10',
    title: 'Database Architecture & SQL Development',
    description: 'PostgreSQL, MySQL, and MongoDB database design, query optimization, indexing, and migration pipelines.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-11',
    title: 'RESTful API & GraphQL Development',
    description: 'Secure API development using Node.js/NestJS/Python, JWT authorization, rate limiting, and OpenAPI documentation.',
    basePrice: 32000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-12',
    title: 'Cybersecurity Audit & Penetration Testing',
    description: 'Vulnerability assessment, OWASP web security testing, server hardening, and security compliance reporting.',
    basePrice: 40000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-13',
    title: 'Computer Networking & LAN/WAN Setup',
    description: 'Office network cabling, Mikrotik router configuration, Wi-Fi mesh setup, and VPN tunnel configuration.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-14',
    title: 'On-Site IT Support & Computer Hardware Fixing',
    description: 'Troubleshooting desktop PCs, laptops, OS reinstallation, malware removal, and hardware upgrades.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-15',
    title: 'Accurate Data Entry & Digitization',
    description: 'High-speed spreadsheet data entry, record cleanup, document scanning, and database data verification.',
    basePrice: 5000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-16',
    title: 'Data Processing & Excel Automation',
    description: 'Advanced Excel formula creation, VBA macro automation, PowerBI reporting, and data scrubbing.',
    basePrice: 10000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-17',
    title: 'Cloud Infrastructure Setup (AWS / GCP / Docker)',
    description: 'Deployment of containerized web apps on Cloud Run, AWS EC2, S3, SSL certificate setup, and CI/CD pipelines.',
    basePrice: 35000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },
  {
    id: 'srv-tech-18',
    title: 'AI & Chatbot Integration Services',
    description: 'Custom Gemini API integration, automated customer service WhatsApp bots, and AI document search.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[6],
  },
  {
    id: 'srv-tech-19',
    title: 'Machine Learning Model Training',
    description: 'Predictive analytics, custom classification models, computer vision, and NLP model fine-tuning.',
    basePrice: 60000,
    durationMinutes: 600,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[4],
  },
  {
    id: 'srv-tech-20',
    title: 'Software Quality Assurance & Automated Testing',
    description: 'Manual SQA, automated Cypress/Playwright regression testing, API Postman collections, and bug reporting.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[0],
    provider: ALL_PROVIDERS[5],
  },

  // --- 2. DIGITAL & MARKETING (15) ---
  {
    id: 'srv-mktg-1',
    title: 'Comprehensive Digital Marketing Campaign',
    description: 'Multi-channel marketing strategy combining Google, Facebook, Instagram, and email lead generation for Pakistani brands.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[7],
  },
  {
    id: 'srv-mktg-2',
    title: 'Search Engine Optimization (SEO)',
    description: 'On-page, technical, and off-page SEO optimization to rank websites on Google Page 1 for local search terms.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[8],
  },
  {
    id: 'srv-mktg-3',
    title: 'Local SEO & Google My Business Setup',
    description: 'GMB profile creation, local citation building, customer review management, and local map pack ranking.',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[9],
  },
  {
    id: 'srv-mktg-4',
    title: 'Social Media Marketing (SMM) Strategy',
    description: 'Targeted campaign management across Instagram, Facebook, and LinkedIn for local business growth.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[7],
  },
  {
    id: 'srv-mktg-5',
    title: 'Social Media Page Management',
    description: 'Monthly content calendar, 15 custom posts/reels design, community engagement, and performance reporting.',
    basePrice: 22000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[8],
  },
  {
    id: 'srv-mktg-6',
    title: 'Content Marketing & Brand Storytelling',
    description: 'Strategic content creation designed to build audience trust, educate buyers, and increase conversion rates.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[9],
  },
  {
    id: 'srv-mktg-7',
    title: 'Email Marketing & Automated Sequence Setup',
    description: 'Mailchimp/Klaviyo email campaign design, newsletter creation, and automated welcome drip sequences.',
    basePrice: 14000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[7],
  },
  {
    id: 'srv-mktg-8',
    title: 'Google Ads (PPC) Search & Display Campaigns',
    description: 'Keyword research, ad copy creation, conversion tracking setup, and ROI-optimized bidding strategy.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[8],
  },
  {
    id: 'srv-mktg-9',
    title: 'Facebook & Instagram Paid Ads Management',
    description: 'Meta pixel setup, custom lookalike audience targeting, ad creative testing, and retargeting campaigns.',
    basePrice: 20000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[9],
  },
  {
    id: 'srv-mktg-10',
    title: 'TikTok Marketing & Viral Video Campaigns',
    description: 'Short-form video concept creation, trending audio strategy, influencer outreach, and TikTok ads setup.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[7],
  },
  {
    id: 'srv-mktg-11',
    title: 'Sales Copywriting & Landing Page Copy',
    description: 'Persuasive sales page copy, website headers, email pitches, and ad copy engineered for high conversions.',
    basePrice: 10000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[8],
  },
  {
    id: 'srv-mktg-12',
    title: 'Professional SEO Content Writing',
    description: 'Research-backed, keyword-rich web content, landing pages, and product descriptions in English and Urdu.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[9],
  },
  {
    id: 'srv-mktg-13',
    title: 'Blog Article Writing & Publication',
    description: '1,500-word engaging blog posts tailored for your industry niche with royalty-free images and meta tags.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[7],
  },
  {
    id: 'srv-mktg-14',
    title: 'English to Urdu Professional Translation',
    description: 'Accurate human translation of business legal documents, websites, marketing flyers, and user manuals.',
    basePrice: 6000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[8],
  },
  {
    id: 'srv-mktg-15',
    title: 'Proofreading & Editing Services',
    description: 'Meticulous grammar, punctuation, sentence structure, and tone correction for academic and corporate documents.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[1],
    provider: ALL_PROVIDERS[9],
  },

  // --- 3. MEDIA & CREATIVE (16) ---
  {
    id: 'srv-media-1',
    title: '4K Video Editing & Color Grading',
    description: 'Professional video post-production for YouTube videos, commercial ads, podcasts, and corporate promos.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },
  {
    id: 'srv-media-2',
    title: 'Professional Photo Retouching & Editing',
    description: 'High-end portrait retouching, background removal, skin smoothing, color balance, and photo manipulation.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[11],
  },
  {
    id: 'srv-media-3',
    title: 'Event & Corporate Photography',
    description: 'On-location professional photography for corporate seminars, brand launch events, and commercial shoots.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[12],
  },
  {
    id: 'srv-media-4',
    title: 'Studio Product Photography',
    description: 'High resolution e-commerce product photos with clean white background, lighting setup, and editing.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },
  {
    id: 'srv-media-5',
    title: 'Wedding & Event Coverage Photography',
    description: 'Full day coverage for Barat, Walima, and Mehendi events with DSLR setup and edited digital album.',
    basePrice: 45000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[11],
  },
  {
    id: 'srv-media-6',
    title: 'Cinematic Videography & Drone Filming',
    description: '4K cinematic video shoot using gimbal stabilization, studio lighting, and licensed 4K aerial drone footage.',
    basePrice: 35000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[12],
  },
  {
    id: 'srv-media-7',
    title: '2D Explainer Video Animation',
    description: 'Engaging 2D character animation videos for business services, apps, and educational products.',
    basePrice: 22000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },
  {
    id: 'srv-media-8',
    title: 'Motion Graphics & Title Animations',
    description: 'Adobe After Effects title reveals, logo animations, lower thirds, and promo transition graphics.',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[11],
  },
  {
    id: 'srv-media-9',
    title: '3D Product Design & Rendering',
    description: 'Photorealistic 3D product modeling, texturing, studio lighting, and high-res CAD rendering.',
    basePrice: 28000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[12],
  },
  {
    id: 'srv-media-10',
    title: '3D Architectural Modeling & Visualizations',
    description: 'Blender / 3ds Max interior and exterior 3D architectural floorplan visualization and walkthroughs.',
    basePrice: 40000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },
  {
    id: 'srv-media-11',
    title: 'Urdu & English Voice Over Studio Services',
    description: 'Professional voice over recording for commercials, e-learning courses, IVR phone systems, and audiobooks.',
    basePrice: 10000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[11],
  },
  {
    id: 'srv-media-12',
    title: 'Audio Editing & Podcast Mastering',
    description: 'Noise cleanup, background hiss removal, audio level normalization, and background score mixing.',
    basePrice: 7000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[12],
  },
  {
    id: 'srv-media-13',
    title: 'Custom Music Production & Jingles',
    description: 'Original background music composition, sound design, jingles, and intro/outro sonic branding.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },
  {
    id: 'srv-media-14',
    title: 'Corporate Presentation & Pitch Deck Design',
    description: 'Investor pitch deck design in PowerPoint / Google Slides with custom graphics, infographics, and charts.',
    basePrice: 15000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[11],
  },
  {
    id: 'srv-media-15',
    title: 'Brochure, Flyer & Print Design',
    description: 'Print-ready CMYK brochures, catalogs, flyers, and magazine ads with vector layout precision.',
    basePrice: 8000,
    durationMinutes: 150,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[12],
  },
  {
    id: 'srv-media-16',
    title: 'Panaflex & Outdoor Signage Design',
    description: 'Large format outdoor billboard design, storefront panaflex boards, and vinyl banner graphics.',
    basePrice: 10000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[2],
    provider: ALL_PROVIDERS[10],
  },

  // --- 4. EDUCATION & TUTORING (11) ---
  {
    id: 'srv-edu-1',
    title: 'School Home Tutoring (Class 1 to 8)',
    description: 'Qualified home tutor for all school subjects including Science, English, Maths, and Social Studies.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[13],
  },
  {
    id: 'srv-edu-2',
    title: 'Mathematics Home & Online Tutoring',
    description: 'Expert maths teacher for Metric, FSc, O-Level, and A-Level algebra, geometry, calculus, and statistics.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[14],
  },
  {
    id: 'srv-edu-3',
    title: 'Physics Tutoring (FSc & O/A Level)',
    description: 'Conceptual physics tutoring focusing on numerical problem solving, past papers, and lab practicals.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[15],
  },
  {
    id: 'srv-edu-4',
    title: 'Chemistry Home & Online Coaching',
    description: 'Organic, inorganic, and physical chemistry tutoring with past paper preparation for Cambridge & Federal board.',
    basePrice: 15000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[13],
  },
  {
    id: 'srv-edu-5',
    title: 'Biology & Pre-Medical Tutoring',
    description: 'Coaching for FSc Pre-Medical and MDCAT biology preparation by experienced medical tutors.',
    basePrice: 16000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[14],
  },
  {
    id: 'srv-edu-6',
    title: 'Spoken English & Fluency Course',
    description: 'Interactive spoken English, accent training, grammar foundation, and conversational practice for adults and students.',
    basePrice: 10000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[15],
  },
  {
    id: 'srv-edu-7',
    title: 'Computer Science (ICS / O-Level) Tutoring',
    description: 'Computer theory, database concepts, algorithms, and logic gate preparation for board examinations.',
    basePrice: 14000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[13],
  },
  {
    id: 'srv-edu-8',
    title: 'Python & JavaScript Programming Coaching',
    description: 'One-on-one coding lessons covering variables, loops, OOP, data structures, and mini project building.',
    basePrice: 20000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[14],
  },
  {
    id: 'srv-edu-9',
    title: 'IELTS Academic & General Exam Prep',
    description: 'Comprehensive IELTS preparation covering Reading, Writing essays, Listening strategies, and Speaking mock tests.',
    basePrice: 18000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[15],
  },
  {
    id: 'srv-edu-10',
    title: 'Board Exam Preparation (Matric & FSc)',
    description: 'Targeted exam preparation, paper solving techniques, time management, and guess papers for top board marks.',
    basePrice: 14000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[13],
  },
  {
    id: 'srv-edu-11',
    title: 'Online One-on-One Virtual Teaching',
    description: 'Flexible virtual teaching sessions via Zoom/Google Meet with screen share and interactive digital whiteboards.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[3],
    provider: ALL_PROVIDERS[14],
  },

  // --- 5. HOME & REPAIR (15) ---
  {
    id: 'srv-home-1',
    title: 'Full House Deep Cleaning Service',
    description: 'Comprehensive house deep cleaning including floor scrubbing, window wiping, kitchen degreasing, and washrooms.',
    basePrice: 8500,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-2',
    title: 'Sofa & Carpet Steam Shampooing',
    description: 'Deep extraction steam cleaning for sofa sets, mattresses, and carpets removing stains and dust mites.',
    basePrice: 4500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-3',
    title: 'Sanitary & Pipe Leakage Plumbing Repair',
    description: 'Fixing leaking pipes, water mixer taps, underground seepage, drain unblocking, and shower installations.',
    basePrice: 2000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[2],
  },
  {
    id: 'srv-home-4',
    title: 'Master Electrician & Home Wiring Check',
    description: 'Short circuit troubleshooting, new wiring installation, distribution board breaker upgrades, and earthing.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-5',
    title: 'Inverter AC Chemical Jet Service',
    description: 'High-pressure chemical jet wash for indoor and outdoor coils, drain pipe cleaning, and pressure check.',
    basePrice: 2500,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-6',
    title: 'AC Installation & Relocation Service',
    description: 'Safe copper piping installation, wall bracket mounting, vacuuming, and indoor unit level positioning.',
    basePrice: 4500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-7',
    title: 'Refrigerator & Deep Freezer Gas Charging',
    description: 'Compressor health test, gas leak fixing, thermostat replacement, and R134a/R600 gas topping up.',
    basePrice: 3800,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-8',
    title: 'Automatic Washing Machine Repair',
    description: 'Top-load and front-load washing machine drain motor, inlet valve, gear box, and PCB repair.',
    basePrice: 2800,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[1],
  },
  {
    id: 'srv-home-9',
    title: 'Microwave Oven Circuit & Magnetron Repair',
    description: 'Fixing non-heating microwave ovens, glass plate turn motor replacement, touch panel fixing, and fuse setup.',
    basePrice: 2200,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-10',
    title: 'Gas / Petrol Generator Servicing & AVR Repair',
    description: 'Generator oil change, spark plug replacement, carburetor tuning, automatic voltage regulator (AVR) setup.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-home-11',
    title: 'Rooftop Solar Panel System Installation',
    description: '5kW to 20kW solar panel structure mounting, hybrid inverter wiring, DC breaker installation, and earthing.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-home-12',
    title: 'Solar Inverter Repair & Cleaning',
    description: 'Solar panel dust washing, inverter error code troubleshooting, MC4 connector replacement, and battery check.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[3],
  },
  {
    id: 'srv-home-13',
    title: 'CCTV Camera System Installation',
    description: 'AHD / IP HD camera mounting, DVR/NVR configuration, mobile app remote viewing setup, and BNC wiring.',
    basePrice: 6000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-14',
    title: 'CCTV Camera Troubleshooting & Repair',
    description: 'Resolving video loss, night vision infrared issues, hard drive recording failures, and power supply repairs.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[0],
  },
  {
    id: 'srv-home-15',
    title: 'Water Tank Cleaning & Disinfection',
    description: 'Underground and overhead water tank mud removal, chemical scrubbing, and chlorine disinfection.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[4],
    provider: ALL_PROVIDERS[2],
  },

  // --- 6. CONSTRUCTION & TRADES (15) ---
  {
    id: 'srv-const-1',
    title: 'Iron Gate & Steel Welding Works',
    description: 'On-site electric arc welding, iron main gate repair, window grill fabrication, and steel structure reinforcement.',
    basePrice: 3500,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[16],
  },
  {
    id: 'srv-const-2',
    title: 'Carpentry & Custom Wooden Furniture Repair',
    description: 'Fixing broken doors, drawer channels, wooden bed polish, door lock fitting, and custom wardrobe adjustments.',
    basePrice: 2500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[17],
  },
  {
    id: 'srv-const-3',
    title: 'Masonry & Brickwork Civil Repairs',
    description: 'Wall plastering, room extension brickwork, boundary wall repair, and cement grout sealing.',
    basePrice: 5000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[18],
  },
  {
    id: 'srv-const-4',
    title: 'Floor & Wall Tile Installation',
    description: 'Porcelain and ceramic floor tile laying, bathroom wall tiling, laser alignment, and waterproof grouting.',
    basePrice: 12000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[16],
  },
  {
    id: 'srv-const-5',
    title: 'Marble Polishing & Diamond Grinding',
    description: 'Sunny Gray, Ziarat White marble floor grinding, chemical mirror polish, and stain removal.',
    basePrice: 15000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[17],
  },
  {
    id: 'srv-const-6',
    title: 'Full House Wall Painting & Waterproofing',
    description: 'Interior matt enamel paint, exterior weather-shield coating, dampness/seepage primer treatment, and wall putty.',
    basePrice: 20000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[18],
  },
  {
    id: 'srv-const-7',
    title: 'Gypsum False Ceiling Installation',
    description: 'Modern gypsum board false ceiling design, cove lighting channels, and pop decorative plaster.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[16],
  },
  {
    id: 'srv-const-8',
    title: 'Roof Seepage & Bitumen Heat Proofing',
    description: 'Rooftop water seepage prevention, elastomeric membrane coating, and heat reflective insulation paint.',
    basePrice: 16000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[17],
  },
  {
    id: 'srv-const-9',
    title: 'Glass Door & Window Fitting',
    description: 'Tempered glass partition fitting, sliding door rollers repair, and frosted glass sheet application.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[18],
  },
  {
    id: 'srv-const-10',
    title: 'Aluminium Section Window Fabrication',
    description: 'Custom aluminium sliding windows, insect screen net fitting, and weatherproof rubber seal installation.',
    basePrice: 14000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[16],
  },
  {
    id: 'srv-const-11',
    title: 'Steel Structure & Shed Fabrication',
    description: 'Industrial steel truss shed building, parking shade installation, and heavy duty steel welding.',
    basePrice: 35000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[17],
  },
  {
    id: 'srv-const-12',
    title: 'General Metal Fabrication Works',
    description: 'Custom iron staircase railings, balcony safety grills, and metal storage racks.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[18],
  },
  {
    id: 'srv-const-13',
    title: 'Modular Kitchen Cabinet Assembly',
    description: 'UV sheet & tactile MDF kitchen cabinet installation, marble countertop cutting, and sink fitting.',
    basePrice: 22000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[16],
  },
  {
    id: 'srv-const-14',
    title: 'Solid Wooden Door Installation',
    description: 'Wooden door frame (chokhat) fitting, solid wood door hanging, mortise lock installation, and polishing.',
    basePrice: 6000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[17],
  },
  {
    id: 'srv-const-15',
    title: 'UPVC Window & Door Fitting',
    description: 'Double glazed energy efficient UPVC window installation, multi-point lock adjustment, and soundproofing.',
    basePrice: 16000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[5],
    provider: ALL_PROVIDERS[18],
  },

  // --- 7. AUTOMOTIVE (12) ---
  {
    id: 'srv-auto-1',
    title: 'Mobile Car Mechanic On-Site Inspection',
    description: 'On-road emergency breakdown assistance, engine misfire troubleshooting, brake shoe replacement, and fluids top-up.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[19],
  },
  {
    id: 'srv-auto-2',
    title: 'Motorcycle General Repair & Engine Tuning',
    description: '70cc / 125cc bike oil change, carburetor cleaning, clutch plate check, chain adjustment, and brake tuning.',
    basePrice: 1200,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[20],
  },
  {
    id: 'srv-auto-3',
    title: 'Auto Electrician & Computer OBD Scanning',
    description: 'Computerized ECU fault code diagnosis, battery wiring check, alternator testing, and power window repair.',
    basePrice: 2500,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[21],
  },
  {
    id: 'srv-auto-4',
    title: 'Car AC Refrigerant Charging & Leak Test',
    description: 'Car AC cooling coil leak testing, compressor clutch check, and genuine R134a refrigerant gas refill.',
    basePrice: 3500,
    durationMinutes: 75,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[19],
  },
  {
    id: 'srv-auto-5',
    title: 'Doorstep Foam Car Wash & Vacuuming',
    description: 'Pressure foam car body wash, interior deep vacuuming, tire shine, and dashboard conditioning at home.',
    basePrice: 1800,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[20],
  },
  {
    id: 'srv-auto-6',
    title: 'Doorstep Heavy Bike Wash & Polish',
    description: 'High-pressure foam bike wash, chain degreasing & lubrication, and chrome polish treatment.',
    basePrice: 1000,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[21],
  },
  {
    id: 'srv-auto-7',
    title: 'Car Denting & Dry Dent Removal',
    description: 'Paintless dry dent removal for minor scratches, bumper realignment, and body panel repair.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[19],
  },
  {
    id: 'srv-auto-8',
    title: 'Car Touchup & Spray Painting',
    description: 'Computerized color matching, scratch touchup, clear coat spray, and body panel paint restoration.',
    basePrice: 8000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[20],
  },
  {
    id: 'srv-auto-9',
    title: 'Tire Puncture & Wheel Alignment Check',
    description: 'Tubeless tire puncture repair, wheel balancing, tire rotation, and air pressure check at doorstep.',
    basePrice: 1500,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[21],
  },
  {
    id: 'srv-auto-10',
    title: 'Car Battery Jumpstart & Replacement',
    description: 'Emergency car battery jumpstart, voltage health test, and on-site new AGS / Exide battery delivery.',
    basePrice: 1500,
    durationMinutes: 30,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[19],
  },
  {
    id: 'srv-auto-11',
    title: 'Comprehensive Pre-Purchase Car Inspection',
    description: '150-point technical car inspection covering engine, transmission, body paint gauge, suspension, and legal docs.',
    basePrice: 5000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[20],
  },
  {
    id: 'srv-auto-12',
    title: 'EFI Engine Tuning & Throttle Body Cleaning',
    description: 'Catalytic converter cleaning, throttle body servicing, spark plug gap setting, and fuel injector testing.',
    basePrice: 4500,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[6],
    provider: ALL_PROVIDERS[21],
  },

  // --- 8. PERSONAL & LIFESTYLE (12) ---
  {
    id: 'srv-life-1',
    title: 'Custom Gents Tailoring & Suit Stitching',
    description: 'Master tailor stitching for Shalwar Kameez, Waistcoats, 2-piece & 3-piece formal suits with custom fitting.',
    basePrice: 3500,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[22],
  },
  {
    id: 'srv-life-2',
    title: 'Bridal & Ladies Dress Designing',
    description: 'Custom designer stitching for Lehnga, Maxis, Designer Lawn suits, lace fitting, and embroidery work.',
    basePrice: 5000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[23],
  },
  {
    id: 'srv-life-3',
    title: 'Doorstep Beauty & Facial Services',
    description: 'At-home herbal facial, waxing, threading, manicure, pedicure, and hair treatment for women.',
    basePrice: 4000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[24],
  },
  {
    id: 'srv-life-4',
    title: 'Gents Haircut & Beard Styling at Home',
    description: 'Professional barber haircut, charcoal facial, head massage, and precision beard grooming at your doorstep.',
    basePrice: 1500,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[22],
  },
  {
    id: 'srv-life-5',
    title: 'Bridal & Party Makeup Artist',
    description: 'Professional HD bridal, Nikkah, and Barat makeup using genuine Kryolan / MAC cosmetics.',
    basePrice: 15000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[23],
  },
  {
    id: 'srv-life-6',
    title: 'Organic Bridal & Eid Mehndi Design',
    description: 'Intricate Pakistani and Arabic organic henna designs for brides, family members, and Eid occasions.',
    basePrice: 3000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[24],
  },
  {
    id: 'srv-life-7',
    title: 'Personal Fitness Coach & Gym Instructor',
    description: 'Customized weight loss, muscle gain training, and diet plan coaching at home or local gym.',
    basePrice: 12000,
    durationMinutes: 60,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[22],
  },
  {
    id: 'srv-life-8',
    title: 'Custom Nutrition & Weight Management Coaching',
    description: 'Personalized meal plans created according to Pakistani home food preferences and health goals.',
    basePrice: 6000,
    durationMinutes: 45,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[23],
  },
  {
    id: 'srv-life-9',
    title: 'Complete Wedding & Birthday Event Planning',
    description: 'End-to-end event management including venue booking, floral stage setup, sound, lighting, and coordination.',
    basePrice: 50000,
    durationMinutes: 480,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[24],
  },
  {
    id: 'srv-life-10',
    title: 'Pakistani Cuisine Catering Services',
    description: 'Authentic Chicken/Mutton Biryani, Karahi, Seekh Kabab, and dessert catering for home parties and events.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[22],
  },
  {
    id: 'srv-life-11',
    title: 'Themed Stage & Floral Decoration',
    description: 'Fresh flower stage decoration, balloon arches, fairy lights, and backdrop design for birthdays and engagement parties.',
    basePrice: 18000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[23],
  },
  {
    id: 'srv-life-12',
    title: 'Intercity Chauffeur & Driver Service',
    description: 'Verified professional driver for city errands or long distance trips across Punjab and Sindh.',
    basePrice: 3000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[7],
    provider: ALL_PROVIDERS[24],
  },

  // --- 9. BUSINESS & LEGAL (10) ---
  {
    id: 'srv-biz-1',
    title: 'FBR Tax Return Filing & NTN Registration',
    description: 'FBR Iris portal tax return filing, wealth statement creation, active taxpayer list (ATL) status, and NTN issuance.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[25],
  },
  {
    id: 'srv-biz-2',
    title: 'Small Business Bookkeeping & Accounting',
    description: 'Monthly ledger maintenance, QuickBooks / Xero entry, financial statements, and balance sheet preparation.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[26],
  },
  {
    id: 'srv-biz-3',
    title: 'Sales Tax & SRB / PRA Registration',
    description: 'Sales tax registration with FBR, Sindh Revenue Board (SRB), or Punjab Revenue Authority (PRA).',
    basePrice: 12000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[27],
  },
  {
    id: 'srv-biz-4',
    title: 'SECP Private Limited Company Registration',
    description: 'End-to-end SECP company registration, incorporation certificate, memorandum of association, and digital signatures.',
    basePrice: 25000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[25],
  },
  {
    id: 'srv-biz-5',
    title: 'Dedicated Virtual Assistant Services',
    description: 'Remote administrative support including email inbox management, appointment scheduling, and customer inquiries.',
    basePrice: 20000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[26],
  },
  {
    id: 'srv-biz-6',
    title: 'Outsourced Customer Support Agent',
    description: '24/7 WhatsApp, live chat, and voice call support agent for e-commerce and local service businesses.',
    basePrice: 18000,
    durationMinutes: 300,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[27],
  },
  {
    id: 'srv-biz-7',
    title: 'HR Consulting & Employee Contract Drafting',
    description: 'Employee handbook creation, offer letters, NDA agreements, performance review frameworks, and payroll setup.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[25],
  },
  {
    id: 'srv-biz-8',
    title: 'Legal Partnership & Rent Agreement Drafting',
    description: 'Drafting legal deeds, tenancy agreements, partnership agreements, and affidavit attestation assistance.',
    basePrice: 8000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[26],
  },
  {
    id: 'srv-biz-9',
    title: 'ATS-Friendly CV & LinkedIn Optimization',
    description: 'Professional resume rewrite targeting ATS keyword screening, cover letter drafting, and LinkedIn profile redesign.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[27],
  },
  {
    id: 'srv-biz-10',
    title: 'Business Feasibility & Financial Modeling',
    description: 'Comprehensive business startup financial projections, cashflow forecasts, and market feasibility reports.',
    basePrice: 30000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[8],
    provider: ALL_PROVIDERS[25],
  },

  // --- 10. AGRICULTURE & GARDENING (8) ---
  {
    id: 'srv-agri-1',
    title: 'Farm Soil Testing & Crop Consulting',
    description: 'Agricultural soil NPK analysis, crop disease advisory, fertilizer recommendations, and yield optimization.',
    basePrice: 8000,
    durationMinutes: 180,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[28],
  },
  {
    id: 'srv-agri-2',
    title: 'Drip & Sprinkler Irrigation Installation',
    description: 'Water-saving agricultural drip irrigation setup, solar pump connection, and filtration system installation.',
    basePrice: 25000,
    durationMinutes: 360,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[29],
  },
  {
    id: 'srv-agri-3',
    title: 'Agricultural Tractor & Land Laser Leveling',
    description: 'Tractor land plowing, rotavator soil turning, and precision GPS laser land leveling for farmlands.',
    basePrice: 12000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[30],
  },
  {
    id: 'srv-agri-4',
    title: 'Termite & Anti-Pest Spray Treatment',
    description: 'Chemical termite proofing for home foundations, bedbug eradication, and agricultural crop pest spray.',
    basePrice: 6000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[28],
  },
  {
    id: 'srv-agri-5',
    title: 'Lawn Landscaping & Garden Design',
    description: 'Custom home lawn grass installation, rockery design, ornamental flower planting, and garden lighting.',
    basePrice: 15000,
    durationMinutes: 240,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[29],
  },
  {
    id: 'srv-agri-6',
    title: 'Regular Home Gardener Maintenance',
    description: 'Bi-weekly lawn mowing, hedge trimming, plant fertilization, weeding, and watering routine.',
    basePrice: 4000,
    durationMinutes: 90,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[30],
  },
  {
    id: 'srv-agri-7',
    title: 'Plant Nursery Delivery & Indoor Plants',
    description: 'Delivery of potted indoor plants, fruit saplings, organic soil manure, and ceramic planters.',
    basePrice: 5000,
    durationMinutes: 120,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[28],
  },
  {
    id: 'srv-agri-8',
    title: 'Tree Pruning & Safe Removal Services',
    description: 'Safe trimming of overgrown tree branches near power lines, stump removal, and blue waste disposal.',
    basePrice: 7000,
    durationMinutes: 150,
    isAvailable: true,
    category: ALL_CATEGORIES[9],
    provider: ALL_PROVIDERS[29],
  },
];
